// Copyright (C) 2025 Kinet Labs, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the Apache-2.0 license as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// Apache-2.0 license for more details.
//
// You should have received a copy of the Apache-2.0 license
// along with this program.  If not, see <http://www.apache.org/licenses/>.

#pragma once

// WARNING: THIS FILE CONTAINS GENERATED CODE, DO NOT EDIT MANUALLY! If
// you need changes, change the code generator or its inputs instead. This
// file was generated by running the following command:
//
//    util/ctypes/codegen/cg-ctypes -s category/execution/ctypes/v1 c -p
//    /home/ken/src/kinet -fclang-format-19

/**
 * @file
 *
 * C layout-compatible types describing Kinet blockchain extensions to
 * Ethereum
 */

#include <category/execution/ethereum/core/base_ctypes.h>
#include <stdint.h>

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/// Fields of a proposed Kinet block that are known at the start of execution
/// and are extensions, i.e., they are not part of the Ethereum specification
struct kinet_c_native_block_input
{
    kinet_c_uint256_ne base_fee_trend;  ///< Trend accumulator
    kinet_c_uint256_ne base_fee_moment; ///< Moment accumulator
};

// clang-format on

#ifdef __cplusplus
} // extern "C"
#endif
